use_frameworks!

target 'MGLandingKit_Example' do
  pod 'MGLandingKit', :path => '../'
  pod 'MGTemplateKit', :git => 'https://haraldbregu:4a4d1162147e80549f22cafb59060bdf59c4934a@github.com/HaraldBregu/MGTemplateKit.git'
  pod 'SDWebImage', '~> 4.0'
end
